// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RouteLink.Domain.Enums;
using RouteLink.Infrastructure.Persistence;

#nullable disable

namespace RouteLink.Infrastructure.Migrations
{
    [DbContext(typeof(RouteLinkDbContext))]
    partial class RouteLinkDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RouteLink.Domain.Entities.FuelRefill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Liters")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 4326)");

                    b.Property<decimal>("Odometer")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<string>("ReceiptPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("TransportId")
                        .HasColumnType("integer");

                    b.Property<int?>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("TransportId");

                    b.HasIndex("TripId");

                    b.ToTable("FuelRefills", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.FuelRefillValidation", b =>
                {
                    b.Property<int>("FuelRefillId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsumptionMismatch")
                        .HasColumnType("boolean");

                    b.Property<string>("RejectionComment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FuelRefillId");

                    b.ToTable("FuelRefillValidations", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.Transport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FuelConsumptionPer100Km")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("PlateNumber")
                        .IsUnique();

                    b.ToTable("Transports", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DriverUserId")
                        .HasColumnType("integer");

                    b.Property<string>("EndPoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<ExecutionStatus>("ExecutionStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasConversion<string>();


                    b.Property<decimal>("PlannedDistanceKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TransportId")
                        .HasColumnType("integer");

                    b.Property<string>("TripNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("DriverUserId");

                    b.HasIndex("TransportId");

                    b.HasIndex("TripNumber")
                        .IsUnique();

                    b.ToTable("Trips", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.TripDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<int>("TripId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("TripDocuments", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.TripDocumentValidation", b =>
                {
                    b.Property<int>("TripDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("RejectionComment")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("RejectionReasonCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TripDocumentId");

                    b.ToTable("TripDocumentValidations", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Phone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.FuelRefill", b =>
                {
                    b.HasOne("RouteLink.Domain.Entities.User", "DriverUser")
                        .WithMany("FuelRefills")
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RouteLink.Domain.Entities.Transport", "Transport")
                        .WithMany("FuelRefills")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RouteLink.Domain.Entities.Trip", "Trip")
                        .WithMany("FuelRefills")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DriverUser");

                    b.Navigation("Transport");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.FuelRefillValidation", b =>
                {
                    b.HasOne("RouteLink.Domain.Entities.FuelRefill", "FuelRefill")
                        .WithOne("Validation")
                        .HasForeignKey("RouteLink.Domain.Entities.FuelRefillValidation", "FuelRefillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelRefill");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.Trip", b =>
                {
                    b.HasOne("RouteLink.Domain.Entities.User", "DriverUser")
                        .WithMany("DriverTrips")
                        .HasForeignKey("DriverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RouteLink.Domain.Entities.Transport", "Transport")
                        .WithMany("Trips")
                        .HasForeignKey("TransportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DriverUser");

                    b.Navigation("Transport");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.TripDocument", b =>
                {
                    b.HasOne("RouteLink.Domain.Entities.Trip", "Trip")
                        .WithMany("TripDocuments")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.TripDocumentValidation", b =>
                {
                    b.HasOne("RouteLink.Domain.Entities.TripDocument", "TripDocument")
                        .WithOne("Validation")
                        .HasForeignKey("RouteLink.Domain.Entities.TripDocumentValidation", "TripDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TripDocument");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.FuelRefill", b =>
                {
                    b.Navigation("Validation");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.Transport", b =>
                {
                    b.Navigation("FuelRefills");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.Trip", b =>
                {
                    b.Navigation("FuelRefills");

                    b.Navigation("TripDocuments");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.TripDocument", b =>
                {
                    b.Navigation("Validation");
                });

            modelBuilder.Entity("RouteLink.Domain.Entities.User", b =>
                {
                    b.Navigation("DriverTrips");

                    b.Navigation("FuelRefills");
                });
#pragma warning restore 612, 618
        }
    }
}
